debug: false

caching:
    config: true
    templates: true
    request: false
    duration: 100
    authenticated: false
    thumbnails: true
    translations: true

reserves:
  mail:
    from: reservas@jerezfreecitytours.com
    to: 
      - freecitytourjerez@yahoo.es
      - carolinamonterogarcia84@gmail.com
#      - jmpantoja@gmail.com
    subject: Nueva reserva
