entries:
    searchable: false
    name: Entries
    singular_name: Entry
    fields:
        slug:
            type: slug
            uses: title_es
            group: content
        title_es:
            type: text
            class: large
            group: content
        title_en:
            type: text
            class: large
            group: content
        teaser_es:
            type: text
            class: large
            group: content
        teaser_en:
            type: text
            class: large
            group: content
        gallery:
            type: imagelist
            group: content
        seo:
            type: seo
            group: "SEO settings"
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    default_status: publish
    sort: -datepublish
    recordsperpage: 10
    icon_many: "fa:gift"
    icon_one: "fa:gift"

reserves:
    searchable: false
    name: Reserves
    singular_name: Reserve
    fields:
        title:
            type: text
            class: large
            readonly: true
            group: content
        name:
            type: text
            class: large
            group: content
        persons:
            type: integer
            class: small
            group: content
        date:
            type: datetime
            class: large
            group: content
        contact:
            type: textarea
            class: large
            group: content
        uuid:
            type: text
            class: large
            group: content
    icon_many: "fa:gift"
    icon_one: "fa:gift"

