entries:
    name: Entries
    singular_name: Entry
    fields:
        title:
            type: text
            class: large
            group: content
        slug:
            type: slug
            uses: title
            group: content
        teaser:
            type: text
            class: large
            group: content
        gallery:
            type: imagelist
            group: content
#        geolocation:
#            type: geolocation
#            group: content
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    default_status: publish
    sort: -datepublish
    recordsperpage: 10
    icon_many: "fa:gift"
    icon_one: "fa:gift"

reserves:
    name: Reserves
    singular_name: Reserve
    fields:
        title:
            type: text
            class: large
            readonly: true
            group: content
        name:
            type: text
            class: large
            group: content
        contact:
            type: text
            class: large
            group: content
        date:
            type: datetime
            class: large
            group: content
    icon_many: "fa:gift"
    icon_one: "fa:gift"

