# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

en-main:
    - label: Home
      route: en-homepage
      class: first

    - label: Reserve
      route: en-reserve
      class: reserve

    - label: Places
      route: en-places


es-main:
    - label: Inicio
      route: es-homepage
      class: first

    - label: Reservas
      route: es-reserve
      class: reserve

    - label: Lugares
      route: es-places



#    - label: Second item
#      path: entry/1
#      submenu:
#          - label: Sub 1
#            path: entry/2
#          - label: Sub 2
#            class: menu-item-class
#            path: entry/3
#          - label: Sub 3
#            path: entry/4
#          - label: Sub 4
#            class: sub-class
#            path: page/3
#    - label: All pages
#      path: pages/
#    - label: The Bolt site
#      link: http://bolt.cm
#      class: last
