# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

en-main:
    - label: Home
      route: en-homepage
      class: first

    - label: Booking
      route: en-reserve
      class: reserve

    - label: Places
      route: en-places


es-main:
    - label: Inicio
      route: es-homepage
      class: first

    - label: Reservas
      route: es-reserve
      class: reserve

    - label: Lugares
      route: es-places