# This file defines user-definable routes for the frontend of your Bolt website.
# Check below for examples, or read the documentation at
# https://docs.bolt.cm/templates/templates-routes#routing

# ------------------------------------------------------------------------------
# Place your own routes here, that have a HIGHER priority than the default routes.



# ------------------------------------------------------------------------------
# These are the routes defining the default behaviour of Bolt's frontend.
# Changing these might give unexpected results or even break your website. If
# possible, only add NEW routes above or below these.

homepage:
    path: /
    defaults:
        _controller: controller.freecity:home

en-homepage:
    path: /en
    defaults:
        _controller: controller.frontend:homepage

es-homepage:
    path: /es
    defaults:
        _controller: controller.frontend:homepage


en-reserve:
    path: /en/booking
    defaults:
        _controller: controller.freecity:reserve

es-reserve:
    path: /es/reservas
    defaults:
        _controller: controller.freecity:reserve

en-reserve-done:
    path: /en/booking/confirmation
    defaults:
        _controller: controller.freecity:confirmation

es-reserve-done:
    path: /es/reservas/confirmacion
    defaults:
        _controller: controller.freecity:confirmation


en-places:
    path: /en/places
    defaults:
        _controller: controller.freecity:places

es-places:
    path: /es/lugares
    defaults:
        _controller: controller.freecity:places

preview:
    path: /preview/{contenttypeslug}
    defaults:
        _controller: controller.frontend:preview
    requirements:
        contenttypeslug: controller.requirement:anyContentType
